"""Pydantic schemas for Movie payloads and responses.

Fields mirror README casing (e.g., `Name`, `CDNImage`). `ReleaseDate` is optional
to accommodate seed data and partial updates.
"""

from pydantic import BaseModel
from typing import Optional
from datetime import date

class MovieBase(BaseModel):
    """Shared movie attributes used across create/read models."""
    Name: str
    Image: str
    CDNImage: str
    ReleaseDate: Optional[date] = None
    ActorsList: str
    language: str
    duration: int
    CDN_VIDEO: str
    description: str
    createdby: str
    lastupdated: str
    lastupdatedby: str
    genre: str
    directedby: str
    certificatetype: str

class MovieCreate(MovieBase):
    """Input model for creating a movie."""

class MovieRead(MovieBase):
    """Response model including autogenerated `movieid`."""
    movieid: int

    class Config:
        from_attributes = True
