"""Pydantic schemas for Movie payloads and responses.

Fields mirror README casing (e.g., `Name`, `CDNImage`). `ReleaseDate` is optional
to accommodate seed data and partial updates.
"""

from pydantic import BaseModel
from typing import Optional
from datetime import date

class MovieBase(BaseModel):
    """Shared movie attributes used across create/read models."""
    Name: str
    Image: str
    CDNImage: str
    ReleaseDate: Optional[date] = None
    ActorsList: str
    language: str
    duration: int
    CDN_VIDEO: str
    description: str
    createdby: str
    lastupdated: str
    lastupdatedby: str
    genre: str
    directedby: str
    certificatetype: str
    published: bool = False

class MovieCreate(MovieBase):
    """Input model for creating a movie."""

class MovieRead(MovieBase):
    """Response model including autogenerated `movieid`."""
    movieid: int

    class Config:
        from_attributes = True

class MovieUpdate(BaseModel):
    """Partial update payload for movies (admin-only).

    All fields are optional; only provided fields will be updated.
    """
    Name: Optional[str] = None
    Image: Optional[str] = None
    CDNImage: Optional[str] = None
    ReleaseDate: Optional[date] = None
    ActorsList: Optional[str] = None
    language: Optional[str] = None
    duration: Optional[int] = None
    CDN_VIDEO: Optional[str] = None
    description: Optional[str] = None
    createdby: Optional[str] = None
    lastupdated: Optional[str] = None
    lastupdatedby: Optional[str] = None
    genre: Optional[str] = None
    directedby: Optional[str] = None
    certificatetype: Optional[str] = None
    published: Optional[bool] = None
