"""Pydantic schemas for User payloads.

- `UserCreate`: input model for signup; includes plaintext `password` (hashed server-side)
- `UserRead`: output model for responses; includes autogenerated `userid`
"""

from pydantic import BaseModel, EmailStr

class UserBase(BaseModel):
    """Common fields shared across user payloads.

    Using README-specified field names to maintain frontend compatibility.
    """
    firstname: str
    lastname: str
    role: str = "user"
    email: EmailStr
    phonenumber: str
    isPremiumUser: bool = False

class UserCreate(UserBase):
    """Signup input including plaintext password (to be hashed)."""
    password: str

class UserRead(UserBase):
    """Response model including server-generated `userid`."""
    userid: int

    class Config:
        from_attributes = True

class UserPayload(BaseModel):
    email: str
    password: str
