"""Authentication routes: signup and login.

Detailed behavior:
- Signup: Ensures unique email, hashes password using bcrypt via `get_password_hash`,
    persists the `User` ORM entity, and returns a Pydantic `UserRead`.
- Login: Looks up user by email, verifies supplied password against stored hash,
    and issues a JWT (subject=`userid`) for use with the global JWT middleware.

Security & Middleware:
- The JWT middleware exempts `/auth/signup`, `/auth/login`, and `/health`, so these
    endpoints remain accessible without a token. All other routes require `Authorization: Bearer <token>`.

Database & Validation:
- Async SQLAlchemy is used for non-blocking DB I/O; `.scalar_one_or_none()` returns a single
    ORM instance when present or `None` otherwise.
"""

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select


from app.schemas.user import UserCreate, UserRead, UserPayload
from app.schemas.token import Token
from app.core.security import get_password_hash, verify_password, create_access_token
from app.db.session import get_db
from app.db.models.user import User

    
router = APIRouter(prefix="/auth", tags=["auth"])

@router.post("/signup", response_model=UserRead)
async def signup(payload: UserCreate, db: AsyncSession = Depends(get_db)):
    """Register a new user.

    This endpoint accepts a `UserCreate` payload, performs uniqueness checks on the
    email, hashes the password, persists the user, and returns a `UserRead` model.

    Steps breakdown:
    1) Uniqueness check: query by email and reject if taken
    2) Secure transform: hash the plaintext password (never store plaintext)
    3) Persistence: add, commit, and refresh to load autogenerated fields (e.g., `userid`)
    4) Response: return ORM entity as validated Pydantic model
    """
    # 1) Uniqueness check: Execute a SELECT on `users.email` and check if any row exists.
    existing = await db.execute(select(User).where(User.email == payload.email))
    if existing.scalar_one_or_none():
        raise HTTPException(status_code=400, detail="Email already registered")

    # 2) Secure transform: Hash the plaintext password before storing.
    #    Using bcrypt via Passlib (`get_password_hash`) mitigates brute-force risks.
    user = User(
        firstname=payload.firstname,
        lastname=payload.lastname,
        email=payload.email,
        password=get_password_hash(payload.password),
        phonenumber=payload.phonenumber,
        isPremiumUser=payload.isPremiumUser,
    )
    # 3) Persistence: Stage, commit, and refresh to populate autogenerated PK (`userid`).
    db.add(user)
    await db.commit()
    await db.refresh(user)
    # 4) Response: Return the ORM entity; FastAPI + Pydantic handle schema conversion.
    return user

@router.post("/login", response_model=Token)
async def login(payload: UserPayload, db: AsyncSession = Depends(get_db)):
    """Authenticate a user and return a JWT access token.

    Steps breakdown:
    1) Lookup: find the user by email
    2) Verify: compare provided password with stored bcrypt hash
    3) Issue: create a signed JWT whose `sub` claims the user id
    4) Return: send `Token` with `access_token` for use in `Authorization: Bearer`
    """
    # 1) Lookup: Query for the user record associated with the provided email.
    result = await db.execute(select(User).where(User.email == payload.email))
    user = result.scalar_one_or_none()
    # 2) Verify: If user is missing or the password doesn't match, deny access.
    if not user or not verify_password(payload.password, user.password):
        raise HTTPException(status_code=401, detail="Invalid credentials")
    # 3) Issue: Subject is the `userid`. Embed role derived from `isPremiumUser`.
    role = "admin" if getattr(user, "isPremiumUser", False) else "user"
    token = create_access_token(subject=str(user.userid), claims={"role": role})
    # 4) Return: Pydantic `Token` model wraps the JWT in a typed response.
    return Token(access_token=token)
